server:
  port: 8888
spring:
  application:
    name: eurekaconfig
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seven-ocean/springcloud.git #配置git仓库地址
          searchPaths: config #配置仓库路径
          username: seven-ocean #访问git仓库的用户名
          password: zg0030727326 #访问git仓库的用户密码
      label: master #配置仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/