server:
  port: 8888
spring:
  application:
    name: eurekaconfig
  profiles:
    active: dev
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri: https://github.com/seven-ocean/springcloud.git #配置git仓库地址
          searchPaths: share/config #配置仓库路径
          username: seven-ocean #访问git仓库的用户名
          password: zg0030727326 #访问git仓库的用户密码
      label: master #配置仓库的分支
  rabbitmq:
          host: 127.0.0.1
          port: 5672
          username: guest
          password: guest
          virtualHost: /
          publisherConfirms: true
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/