eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: eurekafeign
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
# 熔断器
feign:
  hystrix:
    enabled: true