server:
  port: 8762
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    sleuth:
      sampler:
        probability : 1
        percentage : 1
  application:
    name: eurekaclient
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh